application: peterhofguide
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /styles
  static_dir: static/css

- url: /scripts
  static_dir: static/js

- url: /images
  static_dir: static/img

- url: /.*
  script: web_handler.py